apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend-route
  namespace: wms
spec:
  parentRefs:
  - name: wms-gateway
    namespace: traefik
  hostnames:
  - "app.datanetwork.online"
  - "app.localtest.me"           # ‚Üê useful for local testing
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: frontend-test
      port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-route
  namespace: wms
spec:
  parentRefs:
  - name: wms-gateway
    namespace: traefik
  hostnames:
  - "api.datanetwork.online"
  - "api.localtest.me"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: backend-test
      port: 80
