apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: wms
type: Opaque
stringData:
  MYSQL_HOST: "140.245.237.157"  # Your external MySQL host
  MYSQL_PORT: "3306"
  MYSQL_USER: "wms_app"
  MYSQL_PASSWORD: "Ajaykumar@12."
  MYSQL_DATABASE: "waste_management"

---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
stringData:
  api-token: "ZkUQyiqKjOaDsD5yLObULWddvbSvdydta4IQ-C-p"  # Replace with your Cloudflare API token


# PORT=5000
# DB_HOST=140.245.237.157
# DB_USER=wms_app
# DB_PASS=Ajaykumar@12.
# DB_NAME=waste_management
# JWT_SECRET=supersecret_jwt_key_2025_wms
# EMAIL_USER=yourgmail@gmail.com
# EMAIL_PASS=your_app_password_16_chars
# BASE_URL=http://localhost:3000