apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: wms
type: Opaque
stringData:
  DB_HOST: "140.245.237.157"
  DB_USER: "wms_app"
  DB_PASSWORD: "Ajaykumar@12."
  DB_NAME: "waste_management"
  DB_PORT: "3306"
  JWT_SECRET: "supersecret_jwt_key_2025_wms"

  # ðŸ”½ ADD THESE
  PORT: "5000"
  NODE_ENV: "production"
  ALLOWED_ORIGINS: "https://app.datanetwork.online,http://136.115.177.148"
