apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wms-app-tls
  namespace: wms
spec:
  secretName: wms-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - app.datanetwork.online
    - grafana.datanetwork.online
    - prometheus.datanetwork.online
