apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: wms
stringData:
  # Create a Cloudflare API token scoped to: Zone:Zone:Read, Zone:Cache Purge, Zone:DNS:Edit for your zone
  CLOUDFLARE_API_TOKEN: "ZkUQyiqKjOaDsD5yLObULWddvbSvdydta4IQ-C-p"
