apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: datanetwork-wildcard-cert
  namespace: wms
spec:
  secretName: datanetwork-tls
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
  dnsNames:
  - "datanetwork.online"
  - "*.datanetwork.online"