apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-cloudflare
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "bkajaykumar026@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - dns01:
          cloudflare:
            email: "bkajaykumar026@gmail.com"
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: CLOUDFLARE_API_TOKEN
