apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-app-datanetwork
  namespace: wms
spec:
  secretName: tls-app-datanetwork
  commonName: app.datanetwork.online
  dnsNames:
    - app.datanetwork.online
  issuerRef:
    name: letsencrypt-staging-cloudflare
    kind: ClusterIssuer
