apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-api-datanetwork
  namespace: wms
spec:
  secretName: tls-api-datanetwork
  commonName: api.datanetwork.online
  dnsNames:
    - api.datanetwork.online
  issuerRef:
    name: letsencrypt-staging-cloudflare
    kind: ClusterIssuer
