apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend-route
  namespace: wms
spec:
  parentRefs:
    - name: wms-gateway
  hostnames:
    - "app.datanetwork.online"
  rules:
    - backendRefs:
        - name: frontend
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-route
  namespace: wms
spec:
  parentRefs:
    - name: wms-gateway
  hostnames:
    - "api.datanetwork.online"
  rules:
    - backendRefs:
        - name: backend
          port: 80
