apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-config
  namespace: wms
type: Opaque
stringData:
  config.yaml: |
    tunnel: k8s-envoy
    credentials-file: /etc/cloudflared/credentials.json

    ingress:
      # ðŸ”¹ Uploaded images
      - hostname: app.datanetwork.online
        path: /uploads/*
        service: http://envoy-wms-wms-gateway-00260609.envoy-gateway-system.svc.cluster.local:80

      # ðŸ”¹ App + API traffic
      - hostname: app.datanetwork.online
        service: http://envoy-wms-wms-gateway-00260609.envoy-gateway-system.svc.cluster.local:80

      # ðŸ”¹ Fallback
      - service: http_status:404
