apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-route
  namespace: wms
spec:
  parentRefs:
    - name: wms-gateway
  hostnames:
    - api.datanetwork.online
  rules:
    - backendRefs:
        - name: backend-service
          port: 5000
