apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-wms
  namespace: wms
spec:
  secretName: wildcard-wms-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - "*.datanetwork.online"
    - "datanetwork.online"
