apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: supportair-ingress
  namespace: supportair
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "supportair-ip"
spec:
  rules:
  - http:
      paths:
      - path: /api/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: supportair-backend
            port:
              number: 5000
      - path: /uploads/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: supportair-backend
            port:
              number: 5000
      - path: /socket.io/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: supportair-backend
            port:
              number: 5000
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: supportair-frontend
            port:
              number: 80