# metallb-config.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: wms-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.0.1.200-10.0.1.250  # Using upper range of your subnet
  autoAssign: false  # Prevent automatic assignment to other services
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: wms-l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - wms-ip-pool
  interfaces:
  - eth0  # Primary network interface on AWS EC2