apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: wms-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.0.1.240-10.0.1.250  # Adjust to your VPC subnet range

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: wms-l2
  namespace: metallb-system
spec:
  ipAddressPools:
  - wms-pool