apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: wms-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.0.2.240-10.0.2.250  # Updated for your 10.0.2.0/24 subnet

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: wms-l2
  namespace: metallb-system
spec:
  ipAddressPools:
  - wms-pool