---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-route
  namespace: monitoring 
spec:
  parentRefs:
    - name: wms-gateway
      namespace: wms 
      sectionName: https
  hostnames:
    - "grafana.datanetwork.online"
  rules:
    - backendRefs:
        - name: prometheus-stack-grafana
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus-route
  namespace: monitoring 
spec:
  parentRefs:
    - name: wms-gateway
      namespace: wms
      sectionName: https
  hostnames:
    - "prometheus.datanetwork.online"
  rules:
    - backendRefs:
        - name: prometheus-stack-kube-prom-prometheus
          port: 9090
