apiVersion: v1
kind: Secret
metadata:
  name: wms-secrets
  namespace: wms
type: Opaque
stringData:
  # MySQL Configuration
  DB_HOST: "140.245.237.157"
  DB_USER: "wms_app"
  DB_PASS: "Ajaykumar@12."
  DB_NAME: "waste_management"
  
  # JWT Secret
  JWT_SECRET: "supersecret_jwt_key_2025_wms"
  
  # Email Configuration (UPDATE THESE!)
  EMAIL_USER: "youremail@gmail.com"
  EMAIL_PASS: "your_16_char_app_password"