apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: supportair
type: Opaque
stringData:
  DB_HOST: "140.245.237.157"
  DB_USER: "wms_app"
  DB_PASS: "Ajaykumar@12."
  DB_NAME: "waste_management"
  JWT_SECRET: "supersecret_jwt_key_2025_wms"
  EMAIL_USER: "yourgmail@gmail.com"
  EMAIL_PASS: "your_app_password_16_chars"