# wildcard-certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-datanetwork-online
  namespace: wms
spec:
  secretName: wildcard-datanetwork-online-tls
  issuerRef:
    name: cloudflare-letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - "*.datanetwork.online"
  - "datanetwork.online"