apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: wms
type: Opaque
stringData:
  DB_HOST: "140.245.237.157"
  DB_PORT: "3306"           # default MySQL port - change if different
  DB_NAME: "waste_management"
  DB_USER: "wms_app"
  DB_PASSWORD: "Ajaykumar@12."
  JWT_SECRET: "supersecret_jwt_key_2025_wms"
  NODE_ENV: "production"
