name: Build & Push Docker Images

on:
  push:
    branches: [ develop, test] 
  workflow_dispatch:         #triger  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      
      - name: Checkout Repository #Code checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} 

      # Install JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Create SonarQube project if not exists
      - name: Create SonarQube Project If Not Exists
        run: |
          echo "Attempting to create SonarQube project..."
          curl -s -o /dev/null -w "%{http_code}" \
            -u "${{ secrets.SONAR_TOKEN }}:" \
            -X POST "${{ secrets.SONAR_HOST_URL }}/api/projects/create" \
            -d "project=project-wms" \
            -d "name=project-wms" \
          || echo "Ignoring SonarQube creation error"
        continue-on-error: true 

      # Code Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v3
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=project-wms
            -Dsonar.projectName=project-wms
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Quality Gate
      - name: SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        timeout-minutes: 5
        continue-on-error: true

      #Login to Docker Hub and set short SHA output

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #Build & Push Frontend
      - name: Build and Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ajaykumara/frontend-wms-app:${{ github.run_number }}
            ajaykumara/frontend-wms-app:${{ steps.vars.outputs.sha_short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      #Build & Push Backend
      - name: Build and Push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ajaykumara/backend-wms-app:${{ github.run_number }}
            ajaykumara/backend-wms-app:${{ steps.vars.outputs.sha_short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Success
      - name: Done
        run: |
          echo "Frontend & Backend images pushed successfully!"
    